"use client";
import type { Metadata } from "next";
import "./globals.css";
//it gives acess to user's client. such as window/local cookies only client not server

import { SessionProvider } from "next-auth/react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function ProvidersWrapper({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
        {children} {/** represents our entire application  --> has acess to NextAuth*/}

        
    </SessionProvider>

    
  );
}


/**
 ProvidersWrapper.tsx
import { SessionProvider } from "next-auth/react";

export default function ProvidersWrapper({ children }: { children: React.ReactNode }) {
  return <SessionProvider>{children}</SessionProvider>;
}
 */
